function(mcu_filter_is_directory OUT_VAR IN_VAR)
    set(tmp "")
    foreach(d IN LISTS IN_VAR)
        if (IS_DIRECTORY "${d}")
            list(APPEND tmp "${d}")
        endif()
    endforeach()
    set("${OUT_VAR}" "${tmp}" PARENT_SCOPE)
endfunction()
