# Execute with cmake -P versions-tests.cmake

macro(do_test L R)
  set(eq FALSE)
  set(lt FALSE)
  set(lte FALSE)
  set(gt FALSE)
  set(gte FALSE)
  if(${L} VERSION_EQUAL ${R})
    set(eq TRUE)
  endif()
  if(${L} VERSION_LESS ${R})
    set(lt TRUE)
  endif()
  if(${L} VERSION_LESS_EQUAL ${R})
    set(lte TRUE)
  endif()
  if(${L} VERSION_GREATER ${R})
    set(gt TRUE)
  endif()
  if(${L} VERSION_GREATER_EQUAL ${R})
    set(gte TRUE)
  endif()

  message("testing L=${L} R=${R}")
  message(" ${L} =  ${R} => " ${eq})
  message(" ${L} <  ${R} => " ${lt})
  message(" ${L} <= ${R} => " ${lte})
  message(" ${L} >  ${R} => " ${gt})
  message(" ${L} >= ${R} => " ${gte})
endmacro()

do_test("3" "3")
do_test("3.0" "3.0")
do_test("3.0" "3.1")
do_test("3" "4")
do_test("3.0" "4.0")
do_test("3" "3.0")
