#include <cstdint>
#include <cstddef>
#include <cstdio>
#include "mcu/init-impl.h"

__attribute__((section(".isr_vectors"), used))
uint32_t isr_vectors[74] = {
        (uint32_t) _Reset_Handler,
        (uint32_t) NMI_Handler,
        (uint32_t) HardFault_Handler,
        (uint32_t) MemManage_Handler,
        (uint32_t) BusFault_Handler,
        (uint32_t) UsageFault_Handler,
        0,
        0,
        0,
        0,
        (uint32_t) SVC_Handler,
        (uint32_t) DebugMon_Handler,
        0,
        (uint32_t) PendSV_Handler,
        (uint32_t) SysTick_Handler,
        (uint32_t) WWDG_IRQHandler,
        (uint32_t) PVD_IRQHandler,
        (uint32_t) TAMPER_IRQHandler,
        (uint32_t) RTC_IRQHandler,
        (uint32_t) FLASH_IRQHandler,
        (uint32_t) RCC_IRQHandler,
        (uint32_t) EXTI0_IRQHandler,
        (uint32_t) EXTI1_IRQHandler,
        (uint32_t) EXTI2_IRQHandler,
        (uint32_t) EXTI3_IRQHandler,
        (uint32_t) EXTI4_IRQHandler,
        (uint32_t) DMA1_Channel1_IRQHandler,
        (uint32_t) DMA1_Channel2_IRQHandler,
        (uint32_t) DMA1_Channel3_IRQHandler,
        (uint32_t) DMA1_Channel4_IRQHandler,
        (uint32_t) DMA1_Channel5_IRQHandler,
        (uint32_t) DMA1_Channel6_IRQHandler,
        (uint32_t) DMA1_Channel7_IRQHandler,
        (uint32_t) ADC1_2_IRQHandler,
        (uint32_t) USB_HP_CAN1_TX_IRQHandler,
        (uint32_t) USB_LP_CAN1_RX0_IRQHandler,
        (uint32_t) CAN1_RX1_IRQHandler,
        (uint32_t) CAN1_SCE_IRQHandler,
        (uint32_t) EXTI9_5_IRQHandler,
        (uint32_t) TIM1_BRK_IRQHandler,
        (uint32_t) TIM1_UP_IRQHandler,
        (uint32_t) TIM1_TRG_COM_IRQHandler,
        (uint32_t) TIM1_CC_IRQHandler,
        (uint32_t) TIM2_IRQHandler,
        (uint32_t) TIM3_IRQHandler,
        0,
        (uint32_t) I2C1_EV_IRQHandler,
        (uint32_t) I2C1_ER_IRQHandler,
        0,
        0,
        (uint32_t) SPI1_IRQHandler,
        0,
        (uint32_t) USART1_IRQHandler,
        (uint32_t) USART2_IRQHandler,
        0,
        (uint32_t) EXTI15_10_IRQHandler,
#if MCUCMAKE_USING_STM32CUBE
        (uint32_t) RTC_Alarm_IRQHandler,
#else
        (uint32_t) RTCAlarm_IRQHandler,
#endif
        (uint32_t) USBWakeUp_IRQHandler,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
};
